[1mdiff --git a/pubspec.yaml b/pubspec.yaml[m
[1mindex bc55dfa..936e3ba 100644[m
[1m--- a/pubspec.yaml[m
[1m+++ b/pubspec.yaml[m
[36m@@ -1,89 +1,28 @@[m
 name: uni_help[m
 description: "A new Flutter project."[m
[31m-# The following line prevents the package from being accidentally published to[m
[31m-# pub.dev using `flutter pub publish`. This is preferred for private packages.[m
[31m-publish_to: 'none' # Remove this line if you wish to publish to pub.dev[m
[31m-[m
[31m-# The following defines the version and build number for your application.[m
[31m-# A version number is three numbers separated by dots, like 1.2.43[m
[31m-# followed by an optional build number separated by a +.[m
[31m-# Both the version and the builder number may be overridden in flutter[m
[31m-# build by specifying --build-name and --build-number, respectively.[m
[31m-# In Android, build-name is used as versionName while build-number used as versionCode.[m
[31m-# Read more about Android versioning at https://developer.android.com/studio/publish/versioning[m
[31m-# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.[m
[31m-# Read more about iOS versioning at[m
[31m-# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html[m
[31m-# In Windows, build-name is used as the major, minor, and patch parts[m
[31m-# of the product and file versions while build-number is used as the build suffix.[m
[32m+[m[32mpublish_to: 'none'[m
 version: 1.0.0+1[m
 [m
 environment:[m
   sdk: ^3.13.0[m
 [m
[31m-# Dependencies specify other packages that your package needs in order to work.[m
[31m-# To automatically upgrade your package dependencies to the latest versions[m
[31m-# consider running `flutter pub upgrade --major-versions`. Alternatively,[m
[31m-# dependencies can be manually updated by changing the version numbers below to[m
[31m-# the latest version available on pub.dev. To see which dependencies have newer[m
[31m-# versions available, run `flutter pub outdated`.[m
 dependencies:[m
   flutter:[m
     sdk: flutter[m
 [m
[31m-  # The following adds the Cupertino Icons font to your application.[m
[31m-  # Use with the CupertinoIcons class for iOS style icons.[m
   cupertino_icons: ^1.0.8[m
 [m
 dev_dependencies:[m
   flutter_test:[m
     sdk: flutter[m
 [m
[31m-  # The "flutter_lints" package below contains a set of recommended lints to[m
[31m-  # encourage good coding practices. The lint set provided by the package is[m
[31m-  # activated in the `analysis_options.yaml` file located at the root of your[m
[31m-  # package. See that file for information about deactivating specific lint[m
[31m-  # rules and activating additional ones.[m
   flutter_lints: ^6.0.0[m
 [m
[31m-# For information on the generic Dart part of this file, see the[m
[31m-# following page: https://dart.dev/tools/pub/pubspec[m
[31m-[m
[31m-# The following section is specific to Flutter packages.[m
 flutter:[m
 [m
[31m-  # The following line ensures that the Material Icons font is[m
[31m-  # included with your application, so that you can use the icons in[m
[31m-  # the material Icons class.[m
   uses-material-design: true[m
 [m
   # To add assets to your application, add an assets section, like this:[m
   # assets:[m
   #   - images/a_dot_burr.jpeg[m
   #   - images/a_dot_ham.jpeg[m
[31m-[m
[31m-  # An image asset can refer to one or more resolution-specific "variants", see[m
[31m-  # https://flutter.dev/to/resolution-aware-images[m
[31m-[m
[31m-  # For details regarding adding assets from package dependencies, see[m
[31m-  # https://flutter.dev/to/asset-from-package[m
[31m-[m
[31m-  # To add custom fonts to your application, add a fonts section here,[m
[31m-  # in this "flutter" section. Each entry in this list should have a[m
[31m-  # "family" key with the font family name, and a "fonts" key with a[m
[31m-  # list giving the asset and other descriptors for the font. For[m
[31m-  # example:[m
[31m-  # fonts:[m
[31m-  #   - family: Schyler[m
[31m-  #     fonts:[m
[31m-  #       - asset: fonts/Schyler-Regular.ttf[m
[31m-  #       - asset: fonts/Schyler-Italic.ttf[m
[31m-  #         style: italic[m
[31m-  #   - family: Trajan Pro[m
[31m-  #     fonts:[m
[31m-  #       - asset: fonts/TrajanPro.ttf[m
[31m-  #       - asset: fonts/TrajanPro_Bold.ttf[m
[31m-  #         weight: 700[m
[31m-  #[m
[31m-  # For details regarding fonts from package dependencies,[m
[31m-  # see https://flutter.dev/to/font-from-package[m
